-- Delete Scripts
DELETE FROM PRIVILEGE WHERE MODULE_ID = 1;
DELETE FROM PRIVILEGE WHERE MODULE_ID = 2;

DELETE FROM MODULE WHERE ID = 1;
DELETE FROM MODULE WHERE ID = 2;

DELETE FROM USERROLE WHERE ROLE_NAME = "ROLE_ADMIN";
DELETE FROM USERROLE WHERE ROLE_NAME = "ROLE_USER";

DELETE FROM ROLE WHERE NAME = "ROLE_ADMIN";
DELETE FROM ROLE WHERE NAME = "ROLE_USER";

DELETE FROM USER WHERE USERNAME = "admin@wsolution.com";



-- Insert Scripts
INSERT INTO MODULE (ID, PERMISSION_CODE, STATUS) VALUES (1,"INV", 1);
INSERT INTO MODULE (ID, PERMISSION_CODE, STATUS) VALUES (2,"INV-CUS", 1);

INSERT INTO ROLE (NAME) VALUES ("ROLE_ADMIN");
INSERT INTO ROLE (NAME) VALUES ("ROLE_USER");

INSERT INTO PRIVILEGE (ROLE_NAME, MODULE_ID, STATUS) VALUES ("ROLE_ADMIN",1,1);
INSERT INTO PRIVILEGE (ROLE_NAME, MODULE_ID, STATUS) VALUES ("ROLE_ADMIN",2,1);
INSERT INTO PRIVILEGE (ROLE_NAME, MODULE_ID, STATUS) VALUES ("ROLE_USER",2,1);

INSERT INTO USER (USERNAME, PASSWORD, STATUS, FAILEDATTEMPTS, CREATEDBY, CREATEDDATE, MODIFIEDBY, MODIFIEDDATE) VALUES ("admin@wsolution.com", "$2a$10$o1oVQ9vnVTtNwEKRquoRLeKCj8YaEAMRgnGGNxKrXUqe.r1hgnwGy", 1, 0, "SYSTEM", '2020-10-11 17:17:17', "SYSTEM", '2020-10-11 17:17:17');

INSERT INTO USERROLE (USER_USERNAME, ROLE_NAME) VALUES ("admin@wsolution.com", "ROLE_ADMIN");
INSERT INTO USERROLE (USER_USERNAME, ROLE_NAME) VALUES ("admin@wsolution.com", "ROLE_USER");
